package com.topsai.meteringsocket;
import android.app.*;
import android.os.*;
import android.content.*;
import android.graphics.Color;
import android.graphics.Typeface;
import android.graphics.drawable.GradientDrawable;
import android.net.Uri;
import android.provider.Settings;
import android.view.*;
import android.widget.*;
import org.json.*;
import java.net.*;
import java.io.*;
import java.nio.charset.StandardCharsets;
import java.util.Locale;
import java.util.concurrent.*;

public class MainActivity extends Activity {
 final ExecutorService worker=Executors.newSingleThreadExecutor();final Handler ui=new Handler(Looper.getMainLooper());
 JSONArray profiles=new JSONArray();JSONObject latest=new JSONObject();String host="",token="";int generation=0,selected=0;boolean active=false,busy=false;
 LinearLayout root;TextView connection,reading,inputs,relay,externalRelay,details;Button on,off,reset,timer,externalOn,externalOff,externalReset,externalTimer;Spinner devices;
 final String[] ruleCodes={"manual","input1","input2","both","either","both_follow","either_follow"};
 final String[] ruleLabels={"仅手动控制","开关1按下允许","开关2按下允许","两个都按下允许","任一个按下允许","自动跟随：两个都按下","自动跟随：任一个按下"};
 @Override public void onCreate(Bundle b){super.onCreate(b);try{profiles=new JSONArray(Vault.load(this));}catch(Exception e){Toast.makeText(this,"读取设备凭据失败，请重新配对",Toast.LENGTH_LONG).show();}build();if(profiles.length()>0)select(Math.min(getPreferences(0).getInt("selected",0),profiles.length()-1));}
 int dp(int n){return Math.round(n*getResources().getDisplayMetrics().density);}
 TextView label(LinearLayout parent,String s,int size){TextView t=new TextView(this);t.setText(s);t.setTextSize(size);t.setTextColor(Color.rgb(24,49,46));t.setPadding(0,dp(7),0,dp(7));parent.addView(t);return t;}
 LinearLayout card(){LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setPadding(dp(20),dp(12),dp(20),dp(16));GradientDrawable bg=new GradientDrawable();bg.setColor(Color.WHITE);bg.setCornerRadius(dp(22));c.setBackground(bg);LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.bottomMargin=dp(16);root.addView(c,p);return c;}
 Button button(LinearLayout p,String s,Runnable action){Button b=new Button(this);b.setText(s);b.setAllCaps(false);p.addView(b);b.setOnClickListener(v->action.run());return b;}
 void build(){ScrollView scroll=new ScrollView(this);scroll.setFillViewport(true);root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(dp(22),dp(24),dp(22),dp(24));root.setBackgroundColor(Color.rgb(240,245,244));scroll.addView(root);setContentView(scroll);root.setOnApplyWindowInsetsListener((v,i)->{root.setPadding(dp(22),dp(24)+i.getSystemWindowInsetTop(),dp(22),dp(24)+i.getSystemWindowInsetBottom());return i;});
 TextView title=label(root,"计量插座",30);title.setTypeface(null,Typeface.BOLD);label(root,"家庭 Wi-Fi 直连 · MQTT 可选",14);
 LinearLayout d=card();devices=new Spinner(this);d.addView(devices);updateDevices();devices.setOnItemSelectedListener(new android.widget.AdapterView.OnItemSelectedListener(){public void onItemSelected(android.widget.AdapterView<?> a,View v,int p,long id){if(profiles.length()>0)select(p);}public void onNothingSelected(android.widget.AdapterView<?> a){}});button(d,"＋ 添加 / 修改设备",()->deviceDialog());connection=label(d,"尚未连接设备",14);
 LinearLayout m=card();label(m,"实时计量",15);reading=label(m,"— W",34);details=label(m,"电压 —   电流 —\n累计电量 —",16);inputs=label(m,"开关1 —    开关2 —",16);
 LinearLayout c=card();label(c,"板载磁保持继电器",15);relay=label(c,"板载状态未知",23);on=button(c,"开启板载继电器",()->channelCommand("onboard","/api/relay",json("on",true)));off=button(c,"关闭板载继电器",()->channelCommand("onboard","/api/relay",json("on",false)));reset=button(c,"解除板载保护锁定",()->channelCommand("onboard","/api/reset",new JSONObject()));timer=button(c,"板载关闭倒计时",()->timerDialog("onboard"));button(c,"板载联动 · 保护 · 每日定时",()->rulesDialog("onboard"));label(c,"磁保持状态由驱动脉冲估计，未测量实际触点。原 KEY 保留：长按 3 秒进入配网。",13);
 LinearLayout e=card();label(e,"外接普通继电器 · 独立控制",15);externalRelay=label(e,"外接状态未知",23);externalOn=button(e,"开启外接继电器",()->channelCommand("external","/api/relay",json("on",true)));externalOff=button(e,"关闭外接继电器",()->channelCommand("external","/api/relay",json("on",false)));externalReset=button(e,"解除外接保护锁定",()->channelCommand("external","/api/reset",new JSONObject()));externalTimer=button(e,"外接关闭倒计时",()->timerDialog("external"));button(e,"外接联动 · 保护 · 每日定时",()->rulesDialog("external"));disable();
 LinearLayout s=card();button(s,"计量校准 · 板载驱动方向",()->hardwareDialog());button(s,"Wi-Fi / Home Assistant 配置",()->networkDialog());button(s,"上传固件升级",()->{Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.setType("application/octet-stream");i.addCategory(Intent.CATEGORY_OPENABLE);startActivityForResult(i,20);});button(s,"远程：打开 Home Assistant",()->haDialog());label(s,"首次连接：接入 MeteringSocket 热点，再添加 192.168.4.1 并点首次配对。离家通过 Home Assistant 或 VPN 控制。",13);
 }
 JSONObject json(String k,Object v){JSONObject d=new JSONObject();try{d.put(k,v);}catch(Exception ignored){}return d;}
 JSONObject channelBody(String channel,JSONObject body){try{body.put("channel",channel);}catch(JSONException ignored){}return body;}
 void channelCommand(String channel,String path,JSONObject body){command(path,channelBody(channel,body));}
 JSONObject controller(String channel){JSONObject c="external".equals(channel)?latest.optJSONObject("external"):latest;return c==null?new JSONObject():c;}
 String channelName(String channel){return "external".equals(channel)?"外接继电器":"板载继电器";}
 void updateDevices(){String[] names=new String[Math.max(1,profiles.length())];if(profiles.length()==0)names[0]="请添加设备";for(int i=0;i<profiles.length();i++)names[i]=profiles.optJSONObject(i).optString("name","插座 "+(i+1));devices.setAdapter(new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,names));}
 void select(int i){selected=i;JSONObject p=profiles.optJSONObject(i);if(p==null)return;host=p.optString("host");token=p.optString("token");generation++;latest=new JSONObject();disable();getPreferences(0).edit().putInt("selected",i).apply();poll();}
 void disable(){for(Button b:new Button[]{on,off,timer,reset,externalOn,externalOff,externalTimer,externalReset})if(b!=null)b.setEnabled(false);}
 @Override public void onResume(){super.onResume();active=true;poll();}
 @Override public void onPause(){active=false;generation++;disable();super.onPause();}
 @Override public void onDestroy(){worker.shutdownNow();super.onDestroy();}
 HttpURLConnection open(String address) throws Exception {
  android.net.ConnectivityManager cm=(android.net.ConnectivityManager)getSystemService(CONNECTIVITY_SERVICE);
  for(android.net.Network n:cm.getAllNetworks()){android.net.NetworkCapabilities cap=cm.getNetworkCapabilities(n);if(cap!=null&&cap.hasTransport(android.net.NetworkCapabilities.TRANSPORT_WIFI))return (HttpURLConnection)n.openConnection(new URL(address));}
  return (HttpURLConnection)new URL(address).openConnection();
 }
 JSONObject request(String endpoint,String credential,String path,JSONObject body) throws Exception {
  HttpURLConnection c=open(endpoint+path);c.setConnectTimeout(2500);c.setReadTimeout(3000);c.setInstanceFollowRedirects(false);c.setRequestProperty("Authorization","Bearer "+credential);c.setRequestProperty("Connection","close");
  try{if(body!=null){c.setRequestMethod("POST");c.setDoOutput(true);c.setRequestProperty("Content-Type","application/json");try(OutputStream out=c.getOutputStream()){out.write(body.toString().getBytes(StandardCharsets.UTF_8));}}
   int status=c.getResponseCode();InputStream input=status<400?c.getInputStream():c.getErrorStream();String text=input==null?"{}":Streams.read(input);JSONObject r=new JSONObject(text);if(status!=200)throw new IOException(r.optString("error","HTTP "+status));return r;
  }finally{c.disconnect();}
 }
 void poll(){if(!active||host.isEmpty()||busy)return;busy=true;int g=generation;String h=host,t=token;worker.execute(()->{try{JSONObject r=request(h,t,"/api/state",null);ui.post(()->{if(g==generation&&active){latest=r;render(r);}});}catch(Exception e){ui.post(()->{if(g==generation&&active){connection.setText("连接中断 · 读数已过期\n"+e.getMessage());disable();}});}finally{ui.post(()->{busy=false;if(active)ui.postDelayed(()->poll(),2000);});}});}
 void render(JSONObject s){connection.setText("已连接 · "+s.optString("ip",host)+"\n"+(s.optBoolean("mqtt_connected")?"Home Assistant MQTT 在线":"局域网直连可用"));boolean valid=s.optBoolean("meter_valid");reading.setText(valid?String.format(Locale.CHINA,"%.1f W",s.optDouble("power")):"— W · 计量失联");details.setText(valid?String.format(Locale.CHINA,"%.1f V   ·   %.3f A   ·   %.1f Hz\n累计电量 %.4f kWh",s.optDouble("voltage"),s.optDouble("current"),s.optDouble("frequency"),s.optDouble("energy")):"读数不可用，设备执行保护关闭");inputs.setText("开关1 "+(s.optBoolean("input1")?"按下 ●":"松开 ○")+"    开关2 "+(s.optBoolean("input2")?"按下 ●":"松开 ○")+"\nCF1 原始脉冲 "+(s.has("cf1_count")?Long.toString(s.optLong("cf1_count")):"—")+" · "+(s.has("cf1_frequency")?String.format(Locale.CHINA,"%.2f Hz",s.optDouble("cf1_frequency")):"— Hz")+"\n状态 LED "+(s.optBoolean("led_on")?"亮":"灭"));
 String state=!s.optBoolean("latch_known")?"状态未知":s.optBoolean("latch_estimated")?"估计开启":"估计关闭";if(s.optBoolean("latch_busy"))state+=" · 驱动脉冲中";
 renderController(s,relay,on,off,reset,timer,valid,!s.optBoolean("latch_busy"),"板载 "+state);
 JSONObject ext=s.optJSONObject("external");if(ext==null){externalRelay.setText("外接状态不可用 · 请升级设备固件");for(Button b:new Button[]{externalOn,externalOff,externalReset,externalTimer})b.setEnabled(false);}else renderController(ext,externalRelay,externalOn,externalOff,externalReset,externalTimer,valid,true,"外接 "+(ext.optBoolean("relay")?"已开启":"已关闭"));
 }
 void renderController(JSONObject s,TextView text,Button start,Button stop,Button unlock,Button countdown,boolean valid,boolean ready,String status){boolean fault=s.optBoolean("fault"),follow=s.optString("rule").endsWith("follow");text.setText(status+"\n"+(fault?"保护锁定 · ":"")+reasonText(s.optString("reason"))+"\n倒计时 "+s.optInt("countdown")+" 秒");start.setEnabled(!fault&&!follow&&valid&&ready);stop.setEnabled(true);unlock.setEnabled(fault&&valid);countdown.setEnabled(valid&&!fault);}
 String reasonText(String reason){switch(reason){case "on":return "正常运行";case "off":return "已关闭";case "paused":return "暂停输出，解除锁定后恢复";case "meter_stale":return "计量通信中断";case "overload":return "电流或功率超限";case "interlock":return "输入条件未满足";case "timer":return "倒计时结束";default:return reason;}}
 void command(String path,JSONObject body){if(host.isEmpty()){toast("请先添加设备");return;}String h=host,t=token;int g=generation;worker.execute(()->{try{JSONObject r=request(h,t,path,body);ui.post(()->{if(g==generation&&active){toast("已提交，请以设备返回状态为准");if(r.has("relay")){latest=r;render(r);}poll();}});}catch(Exception e){ui.post(()->{if(g==generation){toast(e.getMessage());disable();}});}});}
 void toast(String s){Toast.makeText(this,s,Toast.LENGTH_LONG).show();}
 LinearLayout form(){LinearLayout p=new LinearLayout(this);p.setOrientation(LinearLayout.VERTICAL);p.setPadding(dp(22),dp(10),dp(22),dp(10));return p;}
 EditText field(LinearLayout p,String hint,String value,boolean secret){label(p,hint,13);EditText e=new EditText(this);e.setSingleLine();e.setText(value);if(secret)e.setInputType(129);p.addView(e);return e;}
 void deviceDialog(){LinearLayout p=form();JSONObject old=profiles.optJSONObject(selected);EditText name=field(p,"名称",old==null?"计量插座":old.optString("name"),false),url=field(p,"设备 IP / 域名",old==null?"192.168.4.1":old.optString("host"),false),key=field(p,"设备令牌（首次配对自动读取）",old==null?"":old.optString("token"),true);button(p,"打开手机 Wi-Fi 设置",()->startActivity(new Intent(Settings.ACTION_WIFI_SETTINGS)));button(p,"从热点首次配对",()->{try{String h=Endpoint.normalize(url.getText().toString());worker.execute(()->{try{JSONObject r=request(h,"","/api/pair",null);ui.post(()->key.setText(r.optString("token")));}catch(Exception e){ui.post(()->toast(e.getMessage()));}});}catch(Exception e){toast(e.getMessage());}});
 AlertDialog dialog=new AlertDialog.Builder(this).setTitle("连接设备").setView(p).setPositiveButton("保存为新设备",null).setNeutralButton("更新当前",null).setNegativeButton("取消",null).create();dialog.setOnShowListener(x->{View.OnClickListener save=v->{try{String h=Endpoint.normalize(url.getText().toString());if(key.getText().length()!=32)throw new IllegalArgumentException("令牌应为32位，请先配对");JSONObject item=new JSONObject();item.put("name",name.getText().toString());item.put("host",h);item.put("token",key.getText().toString());if(v==dialog.getButton(-3)&&profiles.length()>0)profiles.put(selected,item);else {selected=profiles.length();profiles.put(item);}Vault.save(this,profiles.toString());updateDevices();devices.setSelection(selected);select(selected);dialog.dismiss();}catch(Exception e){toast(e.getMessage());}};dialog.getButton(-1).setOnClickListener(save);dialog.getButton(-3).setOnClickListener(save);});dialog.show();}
 void timerDialog(String channel){LinearLayout p=form();EditText sec=field(p,"关闭倒计时秒数，0取消，最多86400","600",false);new AlertDialog.Builder(this).setTitle(channelName(channel)+"关闭倒计时").setView(p).setPositiveButton("保存",(d,w)->{try{channelCommand(channel,"/api/timer",json("seconds",Integer.parseInt(sec.getText().toString())));}catch(Exception e){toast("请输入整数秒数");}}).setNegativeButton("取消",null).show();}
 void rulesDialog(String channel){JSONObject state=controller(channel);LinearLayout p=form();Spinner rule=new Spinner(this);rule.setAdapter(new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,ruleLabels));p.addView(rule);for(int i=0;i<ruleCodes.length;i++)if(ruleCodes[i].equals(state.optString("rule")))rule.setSelection(i);EditText current=field(p,"最大电流 A（大于0，最多16）",state.optString("max_current","10"),false),power=field(p,"最大功率 W（大于0，最多3680）",state.optString("max_power","2200"),false),onTime=field(p,"每日开启 HH:mm（空白禁用）",timeText(state.optInt("schedule_on",-1)),false),offTime=field(p,"每日关闭 HH:mm（空白禁用）",timeText(state.optInt("schedule_off",-1)),false);
 label(p,"允许模式需要开启请求；跟随模式按条件自动输出。故障恢复后需解除锁定。每日定时使用北京时间并需网络校时。保存会撤销手动请求，跟随模式可按条件恢复输出。",13);ScrollView sc=new ScrollView(this);sc.addView(p);
 new AlertDialog.Builder(this).setTitle(channelName(channel)+"联动与保护").setView(sc).setPositiveButton("保存",(d,w)->{try{JSONObject j=new JSONObject();j.put("rule",ruleCodes[rule.getSelectedItemPosition()]);j.put("max_current",Double.parseDouble(current.getText().toString()));j.put("max_power",Double.parseDouble(power.getText().toString()));j.put("schedule_on",parseTime(onTime.getText().toString()));j.put("schedule_off",parseTime(offTime.getText().toString()));channelCommand(channel,"/api/config",j);}catch(Exception e){toast("配置格式错误："+e.getMessage());}}).setNegativeButton("取消",null).show();}
 String timeText(int n){return n<0?"":String.format(Locale.ROOT,"%02d:%02d",n/60,n%60);}int parseTime(String s){if(s.trim().isEmpty())return -1;if(!s.matches("([01][0-9]|2[0-3]):[0-5][0-9]"))throw new IllegalArgumentException("时间为HH:mm");return Integer.parseInt(s.substring(0,2))*60+Integer.parseInt(s.substring(3));}
 int parseLatchPulse(String text){int pulse=Integer.parseInt(text.trim());if(pulse<50||pulse>200)throw new IllegalArgumentException("板载脉冲应为50–200毫秒");return pulse;}
 void hardwareDialog(){LinearLayout p=form();EditText vr=field(p,"电压参考 counts/V",latest.optString("vref","15883.34116"),false),ir=field(p,"电流参考 counts/A",latest.optString("iref","251065.6814"),false),pr=field(p,"功率参考 counts/W",latest.optString("pref","623.0270705"),false);EditText pulse=field(p,"高级：板载驱动脉冲 ms（50–200，默认100）",latest.optString("latch_pulse_ms","100"),false);CheckBox direction=new CheckBox(this);direction.setText("INA 为开启方向（关闭此项反转方向）");direction.setChecked(latest.optBoolean("latch_on_ina",true));p.addView(direction);label(p,"板载方向默认暂定 INA 开启。仅在断开市电、低压供电的继电器测试中核对触点方向，再保存正确方向。界面状态是估计值，不能代替触点测量。CF1 仅显示原始脉冲与频率，不重复计入累计电量。",13);ScrollView sc=new ScrollView(this);sc.addView(p);new AlertDialog.Builder(this).setTitle("计量校准与板载方向").setView(sc).setPositiveButton("保存",(d,w)->{try{JSONObject j=new JSONObject();j.put("vref",Double.parseDouble(vr.getText().toString()));j.put("iref",Double.parseDouble(ir.getText().toString()));j.put("pref",Double.parseDouble(pr.getText().toString()));j.put("latch_on_ina",direction.isChecked());j.put("latch_pulse_ms",parseLatchPulse(pulse.getText().toString()));command("/api/config",j);}catch(Exception e){toast("校准格式错误："+e.getMessage());}}).setNegativeButton("取消",null).show();}
 void networkDialog(){LinearLayout p=form();EditText wifi=field(p,"2.4GHz Wi-Fi 名称（空白不更改）","",false),pass=field(p,"Wi-Fi 密码","",true),mq=field(p,"MQTT 地址（空白关闭）",latest.optString("broker"),false),port=field(p,"MQTT 端口",latest.optString("mqtt_port","1883"),false),user=field(p,"MQTT 用户名",latest.optString("mqtt_user"),false),pw=field(p,"MQTT 密码（空白保留原密码）","",true);ScrollView sc=new ScrollView(this);sc.addView(p);new AlertDialog.Builder(this).setTitle("配网与 Home Assistant").setView(sc).setPositiveButton("保存",(d,w)->{try{JSONObject j=new JSONObject();if(wifi.length()>0){j.put("ssid",wifi.getText());j.put("password",pass.getText());}j.put("broker",mq.getText());j.put("mqtt_port",Integer.parseInt(port.getText().toString()));j.put("mqtt_user",user.getText());if(pw.length()>0)j.put("mqtt_password",pw.getText());command("/api/config",j);}catch(Exception e){toast("请检查端口");}}).setNegativeButton("取消",null).show();}
 void haDialog(){LinearLayout p=form();EditText url=field(p,"Home Assistant 地址（使用已有安全远程入口）",getPreferences(0).getString("ha","http://homeassistant.local:8123"),false);new AlertDialog.Builder(this).setTitle("Home Assistant").setView(p).setPositiveButton("打开",(d,w)->{try{String h=Endpoint.normalize(url.getText().toString());getPreferences(0).edit().putString("ha",h).apply();startActivity(new Intent(Intent.ACTION_VIEW,Uri.parse(h)));}catch(Exception e){toast(e.getMessage());}}).setNegativeButton("取消",null).show();}
 @Override protected void onActivityResult(int req,int result,Intent data){super.onActivityResult(req,result,data);if(req!=20||result!=RESULT_OK||data==null||data.getData()==null)return;Uri file=data.getData();new AlertDialog.Builder(this).setTitle("升级固件").setMessage("上传 ESP32-C3 firmware.bin，继电器会关闭并在成功后重启。").setPositiveButton("升级",(d,w)->upload(file)).setNegativeButton("取消",null).show();}
 void upload(Uri uri){String h=host,t=token;if(h.isEmpty())return;worker.execute(()->{HttpURLConnection c=null;try(InputStream in=getContentResolver().openInputStream(uri)){c=open(h+"/api/ota");c.setConnectTimeout(3000);c.setReadTimeout(30000);c.setRequestMethod("POST");c.setDoOutput(true);c.setRequestProperty("Authorization","Bearer "+t);c.setRequestProperty("Content-Type","multipart/form-data; boundary=SocketFirmware");ByteArrayOutputStream firmware=new ByteArrayOutputStream();byte[] buf=new byte[8192];int read;while((read=in.read(buf))!=-1){if(firmware.size()+read>1900000)throw new IOException("固件过大");firmware.write(buf,0,read);}byte[] payload=firmware.toByteArray();byte[] start="--SocketFirmware\r\nContent-Disposition: form-data; name=\"firmware\"; filename=\"firmware.bin\"\r\nContent-Type: application/octet-stream\r\n\r\n".getBytes(StandardCharsets.UTF_8);byte[] end="\r\n--SocketFirmware--\r\n".getBytes(StandardCharsets.UTF_8);c.setFixedLengthStreamingMode(start.length+payload.length+end.length);try(OutputStream out=c.getOutputStream()){out.write("--SocketFirmware\r\nContent-Disposition: form-data; name=\"firmware\"; filename=\"firmware.bin\"\r\nContent-Type: application/octet-stream\r\n\r\n".getBytes(StandardCharsets.UTF_8));out.write(payload);out.write("\r\n--SocketFirmware--\r\n".getBytes(StandardCharsets.UTF_8));}if(c.getResponseCode()!=200)throw new IOException("固件升级失败");ui.post(()->toast("升级成功，等待设备重启"));}catch(Exception e){ui.post(()->toast(e.getMessage()));}finally{if(c!=null)c.disconnect();}});}
}
